// Generated by insterra

module "instellar_link_pinwheel_ulq" {
  source  = "upmaru/bootstrap/instellar//modules/storage"
  version = "0.8.1"

  access_key            = module.aws_storage_pinwheel_doj.access_key_id
  bucket                = module.aws_storage_pinwheel_doj.name
  host                  = module.aws_storage_pinwheel_doj.host
  insterra_component_id = 290
  region                = var.aws_region
  secret_key            = module.aws_storage_pinwheel_doj.secret_access_key
}
