// Generated by insterra

variable "identifier" {}
module "aws_storage_pinwheel_doj" {
  source  = "upmaru/instellar/aws//modules/storage"
  version = "0.9.3"

  blueprint   = var.identifier
  bucket_name = var.identifier
}
